return {
  {
    "craftzdog/solarized-osaka.nvim",
    name="solosaka",
    lazy=true,
    priority=1000,
  },
  {
    "catppuccin/nvim",
    name="catppuccin",
    lazy=true,
    priority=1000,
  },
  {
    "Shatur/neovim-ayu",
    name="ayu",
    lazy=true,
    priority=1000,
  },
  {
    "Mofiqul/dracula.nvim",
    name="dracula",
    lazy=true,
    priority=1000,
  },
  {
    "maxmx03/fluoromachine.nvim",
    name="fluoromachine",
    lazy=true,
    priority=1000,
  }
}
